# Generated by Django 4.0.4 on 2022-05-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=120)),
                ('thread_body', models.TextField()),
                ('thread_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
            ],
            options={
                'ordering': ['thread_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_body', models.CharField(max_length=160)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('posts_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.thread')),
            ],
        ),
    ]
