# Generated by Django 4.0.4 on 2022-05-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
