# Generated by Django 4.0.4 on 2022-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_post_post_body_alter_thread_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='board',
            field=models.CharField(choices=[('python', 'Python'), ('ffbe', 'FFBE')], default='python', max_length=24),
        ),
    ]
