# Generated by Django 4.0.4 on 2022-05-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0003_thread_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.CharField(choices=[('python', 'Python'), ('ffbe', 'FFBE'), ('high strangeness', 'High Strangeness')], default='python', max_length=24),
        ),
    ]
